colors:
  # Default colors
  primary:
    background: '#0d0f18' #'0x17212a'
    foreground: '0xEBEBEB'

  # Cursor colors
  cursor:
    text: '0x0d0f18'
    cursor: '0xEBEBEB'

  # Normal colors
  normal:
    black:   '0x0d0d0d'
    red:     '0xf35e5e'
    green:   '0x23d18b'
    yellow:  '0xFFC620'
    blue:    '0x1BA6FA'
    magenta: '0xd670d6'
    cyan:    '0x21DEEF'
    white:   '0xEBEBEB'

  # Bright colors
  bright:
    black:   '0x6D7070'
    red:     '0xFF4352'
    green:   '0xB8E466'
    yellow:  '0xFFD750'
    blue:    '0x1BA6FA'
    magenta: '0xA578EA'
    cyan:    '0x73FBF1'
    white:   '0xFEFEF8'
