
# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[general]
allow_concurrent_presets = false

[defaults]
kanata_executable = '/home/linuxbrew/.linuxbrew/bin/kanata' # if empty or omitted, system $PATH will be searched.
kanata_config = ''                                          # if empty or not omitted, kanata default config locations will be used.
tcp_port = 5829                                             # if not specified, defaults to 5829

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. when starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]
normal_mode = 'vim_logo.png'
leader = 'vim_logo.png'
window = 'vim_logo.png'
apps = 'vim_logo.png'
normal_mode_shift_layer = 'vim_logo.png'
normal_mode_ctrl_layer = 'vim_logo.png'
normal_mode_g_layer = 'vim_logo.png'
normal_mode_v_layer = 'vim_logo.png'
normal_mode_v_i_layer = 'vim_logo.png'
normal_mode_d_layer = 'vim_logo.png'
normal_mode_d_i_layer = 'vim_logo.png'
normal_mode_d_shift_layer = 'vim_logo.png'
normal_mode_y_layer = 'vim_logo.png'
normal_mode_y_i_layer = 'vim_logo.png'
normal_mode_replace_single_letter_layer = 'vim_logo.png'

[presets.'main cfg']
kanata_config = '~/.config/kanata/kanata.kbd'
autorun = true
