[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "{image,audio,video}/*", run = "mediainfo" },
  { mime = "application/subrip", run = "mediainfo" },
]

[opener]
edit = [
  { run = '/home/linuxbrew/.linuxbrew/bin/nvim "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*", block = true, for = "windows" },
]
