[colors.bright]
black = "0x6D7070"
blue = "0x1BA6FA"
cyan = "0x73FBF1"
green = "0xB8E466"
magenta = "0xA578EA"
red = "0xFF4352"
white = "0xFEFEF8"
yellow = "0xFFD750"

[colors.cursor]
cursor = "0xEBEBEB"
text = "0x0d0f18"

[colors.normal]
black = "0x0d0d0d"
blue = "0x1BA6FA"
cyan = "0x21DEEF"
green = "0x23d18b"
magenta = "0xd670d6"
red = "0xf35e5e"
white = "0xEBEBEB"
yellow = "0xFFC620"

[colors.primary]
background = "#0d0f18"
foreground = "0xEBEBEB"
